sudo: false
language: node_js
os:
  - linux
  - osx
# Test against Webpack supported NodeJS Versions ( >= 4.7 && !5.x, 6.x, 7.x)
node_js:
  - node
  - "6"
  - "4"
env:
  - export WEBPACK_VERSION="2.2.0-rc.5"
  - export WEBPACK_VERSION="1.14.0"
matrix:
  fast_finish: true
before_install:
  - nvm --version
  - node --version
  - npm --version
before_script:
  - 'if [ "$WEBPACK_VERSION" ]; then npm install webpack@^$WEBPACK_VERSION; fi'
script:
  - npm run build
  - npm test
after_success:
  - bash <(curl -s https://codecov.io/bash)
